# Site settings
title: Interlaken
header_image: /content/pictures/IMG_0649_lores.png
main_image: /content/pictures/IMG_0639_lores.png
footer_image: /content/pictures/IMG_0644_lores.png
credit: Tom Duncan & Sam Jones
email: interlakenmusic@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Thank you for visiting our website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Interlakenmusic
github_username:  interlaken
soundcloud_username: interlaken_music
instagram_username: interlaken_music
# Build settings
markdown: kramdown
maruku:
  use_tex:    false
