# Site settings
title: Homepage of Interlaken
email: aaa@aaa.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting our website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: Samisthebest
github_username:  interlaken

# Build settings
markdown: kramdown
maruku:
  use_tex:    false
